import { NextRequest, NextResponse } from "next/server";
import { supabase } from "@/lib/supabase";
import { checkRateLimit } from "@/lib/rateLimit";
import { Resend } from "resend";

const resend = new Resend(process.env.RESEND_API_KEY);

function isValidEmail(email: string): boolean {
  const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
  return emailRegex.test(email);
}

export async function POST(request: NextRequest) {
  try {
    // Rate limiting
    const ip =
      request.headers.get("x-forwarded-for")?.split(",")[0]?.trim() ||
      request.headers.get("x-real-ip") ||
      "unknown";

    if (!checkRateLimit(ip, 20)) {
      return NextResponse.json(
        { error: "Rate limit exceeded. Try again later." },
        { status: 429 }
      );
    }

    const body = await request.json();
    const { email, company, role, teamSize, auditId, website } = body;

    // Honeypot check — if hidden field is filled, it's a bot
    if (website) {
      // Silently accept to not tip off bots
      return NextResponse.json({ success: true });
    }

    // Validate email
    if (!email || !isValidEmail(email)) {
      return NextResponse.json(
        { error: "Valid email address is required" },
        { status: 400 }
      );
    }

    if (!auditId) {
      return NextResponse.json(
        { error: "Audit ID is required" },
        { status: 400 }
      );
    }

    // Fetch audit data for the email
    const { data: auditData, error: auditError } = await supabase
      .from("audits")
      .select("*")
      .eq("id", auditId)
      .single();

    if (auditError || !auditData) {
      return NextResponse.json(
        { error: "Audit not found" },
        { status: 404 }
      );
    }

    // Store lead in Supabase
    const { error: insertError } = await supabase.from("leads").insert({
      email,
      company: company || null,
      role: role || null,
      team_size: teamSize || null,
      audit_id: auditId,
      created_at: new Date().toISOString(),
    });

    if (insertError) {
      console.error("Lead insert error:", insertError);
      // Don't fail the request if insert fails
    }

    // Send transactional email via Resend
    const appUrl = process.env.NEXT_PUBLIC_APP_URL || "https://spendlens.vercel.app";
    const auditUrl = `${appUrl}/audit/${auditId}`;
    const totalSavings = auditData.total_monthly_savings || 0;
    const annualSavings = auditData.total_annual_savings || 0;

    const toolSummary = (auditData.tools || [])
      .map(
        (t: { tool: string; recommendedAction: string; estimatedMonthlySavings: number }) =>
          `• ${t.tool}: ${t.recommendedAction} (saves $${t.estimatedMonthlySavings}/mo)`
      )
      .join("\n");

    const highSavingsNote =
      totalSavings > 500
        ? "\n\nYour savings potential is significant. A Credex advisor will reach out within 2 business days to help you capture these savings — no obligation.\n"
        : "";

    try {
      await resend.emails.send({
        from: process.env.RESEND_FROM_EMAIL || "SpendLens <noreply@spendlens.app>",
        to: email,
        subject: "Your SpendLens AI Audit",
        html: `
          <div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
            <h1 style="color: #1a1a2e; font-size: 24px;">Your AI Spend Audit Results</h1>
            
            <div style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); border-radius: 12px; padding: 24px; margin: 20px 0; color: white;">
              <p style="font-size: 14px; margin: 0 0 8px 0; opacity: 0.9;">Potential Monthly Savings</p>
              <p style="font-size: 36px; font-weight: bold; margin: 0;">$${totalSavings}/mo</p>
              <p style="font-size: 14px; margin: 8px 0 0 0; opacity: 0.9;">That's $${annualSavings} per year</p>
            </div>

            <h2 style="color: #1a1a2e; font-size: 18px;">Findings</h2>
            <pre style="background: #f5f5f5; padding: 16px; border-radius: 8px; font-size: 13px; white-space: pre-wrap; line-height: 1.6;">${toolSummary}</pre>
            
            ${highSavingsNote ? `<div style="background: #fef3cd; border: 1px solid #ffc107; border-radius: 8px; padding: 16px; margin: 20px 0;"><p style="margin: 0; color: #856404;">${highSavingsNote}</p></div>` : ""}

            <a href="${auditUrl}" style="display: inline-block; background: #667eea; color: white; padding: 12px 24px; border-radius: 8px; text-decoration: none; font-weight: 600; margin: 20px 0;">View Full Audit Report →</a>
            
            <p style="color: #666; font-size: 13px; margin-top: 30px;">This audit was generated by <a href="${appUrl}" style="color: #667eea;">SpendLens</a>, built by <a href="https://credex.rocks" style="color: #667eea;">Credex</a>.</p>
          </div>
        `,
      });
    } catch (emailError) {
      console.error("Resend email error:", emailError);
      // Don't fail the request if email fails
    }

    return NextResponse.json({ success: true });
  } catch (error) {
    console.error("Leads API error:", error);
    return NextResponse.json(
      { error: "Failed to process lead" },
      { status: 500 }
    );
  }
}
